FROM armbuild/debian:wheezy
RUN apt-get update
RUN apt-get install -y build-essential libssl-dev libdb5.1++-dev libboost-all-dev libminiupnpc-dev git
RUN git clone https://github.com/piggycoin/newpiggycoin.git /usr/local/src/piggycoin
RUN cd /usr/local/src/piggycoin/src && make -f makefile.unix USE_UPNP=- USE_IPV6=1 USE_QRCODE=0 && strip newpiggycoind
RUN ln -s /usr/local/src/piggycoin/src/newpiggycoind /usr/local/bin/newpiggycoind
RUN ln -s /usr/local/src/piggycoin/src/newpiggycoind /usr/local/bin/piggycoind
EXPOSE 54481
CMD bash
